export const RESTAURANT_START = 'RESTAURANT_START';
export const RESTAURANT_SUCCESS = 'RESTAURANT_SUCCESS';
export const RESTAURANT_FAILURE = 'RESTAURANT_FAILURE';
export const RESTAURANT_RESET = 'RESTAURANT_RESET';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const GET_RESTAURANTS_BY_MONTH = 'GET_RESTAURANTS_BY_MONTH';
export const RESTAURANT_ADD = 'RESTAURANT_ADD';
export const RESTAURANT_DELETE = 'RESTAURANT_DELETE';

export const RESTAURANT_EDIT = 'RESTAURANT_EDIT';
export const RESTAURANT_PASSWORD_CHANGE = 'RESTAURANT_PASSWORD_CHANGE';
export const GET_LOGGED_IN_RESTAURANT = 'GET_LOGGED_IN_RESTAURANT';

